# default config.yml

# Language (might should be a separate file)
PARSE_ERROR_INVALID_QUANTITY:
  player: The quantity you specified is invalid.
PARSE_ERROR_INVALID_STARTING_BID:
  player: The staring bid you specified is invalid.
PARSE_ERROR_INVALID_BID_INCREMENT:
  player: The bid increment you specified is invalid.
PARSE_ERROR_INVALID_TIME:
  player: The time you specified is invalid.
PARSE_ERROR_INVALID_BID:
  player: The bid amount you specified is invalid.
PARSE_ERROR_INVALID_MAX_BID:
  player: The max bid amount you specified is invalid.
 
AUCTION_FAIL_HAND_IS_EMPTY:
  player: Hold something to auction.
AUCTION_FAIL_QUANTITY_TOO_LOW:
  player: You must offer more than that.
AUCTION_FAIL_INSUFFICIENT_SUPPLY:
  player: You do not have enough of this item.
AUCTION_FAIL_STARTING_BID_TOO_HIGH: 
  player: The starting bid is too high.
AUCTION_FAIL_INCREMENT_TOO_LOW: 
  player: The bid increment is too small.
AUCTION_FAIL_INCREMENT_TOO_HIGH: 
  player: The bid increment is too large.
AUCTION_FAIL_TIME_TOO_LOW: 
  player: The specified time is too short.
AUCTION_FAIL_TIME_TOO_HIGH: 
  player: The specified time is too long.
AUCTION_FAIL_INVALID_OWNER:
  console: A non-player tried to start an auction? 
AUCTION_FAIL_AUCTION_EXISTS:
  player: There is already an auction going on.
AUCTION_FAIL_NO_AUCTION_EXISTS:
  player: There is no auction at this time.
AUCTION_FAIL_CONSOLE:
  console: Console cannot start auctions.
AUCTION_FAIL_NOT_OWNER_CANCEL:
  player: You cannot cancel auctions you did not start.
AUCTION_FAIL_NOT_OWNER_END:
  player: You cannot end auctions you did not start.

BID_SUCCESS_NO_CHALLENGER:
  server: %1 has bid %2 on the %3. 
BID_SUCCESS_OUTBID:
  server: %1 raised the bid to %2, outbidding %3.
BID_SUCCESS_UPDATE_OWN_BID:
  server: %1 raised the bid to %3.
BID_SUCCESS_UPDATE_OWN_MAX_BID:
  player: You raised your own bid to %1. 
BID_FAIL_IS_AUCTION_OWNER:
  player: You cannot bid on your own auction.
BID_FAIL_ALREADY_CURRENT_BIDDER:
  player: You (apparently) can't outbid yourself. 
BID_FAIL_AUTO_OUTBID:
  player: 
BID_FAIL_OUTBID_UNCERTAINTY:
  player:
BID_FAIL_NO_PERMISSION:
  player: You haven't permission to bid.
BID_FAIL_CANT_ALLOCATE_FUNDS:
  player: You haven't the money to bid %1.
BID_FAIL_NO_BIDDER:
  console: A non-player tried to bid on an auction? 
BID_FAIL_CONSOLE:
  console: You can't bid from the console, duh!
BID_FAIL_NO_AUCTION:
  player: There is no auction at this time on which to bid.

AUCTION_CANCEL:
  server: The auction has been cancelled. 
AUCTION_END_NO_BIDS:
  server: The auction ended with no bids.
AUCTION_END_WITH_BIDS:
  server: %1 won the auction for %2 with %3!
AUCTION_START:
  server: Attention, an auction is beginning!
AUCTION_HELP:
  player:
    - Put help here.

AUCTION_INFO_HEADER:
  player:
    - %1 is auctioning %2 %3
    - The current bid is %4 by %6
AUCTION_INFO_ENCHANTMENT:
  player: Enchantment: %1
AUCTION_INFO_FOOTER:
  player: 
AUCTION_INFO_NO_AUCTION:
  player: Nothing is being auctioned at this time.
