name: floAuction
version: 3.0.0
description: Auction plugin for economies.
author: flobi
website: http://dev.bukkit.org/server-mods/floauction/
depend: Vault
softdepend: WhatIsIt

main: com.flobi.floAuction3.floAuction
database: false

commands:
  auction:
    description: General auction command.
    usage: Type /<command> for instructions.
  bid:
    description: Bid on auctions.
    usage: /<command> [bit amount] [max bid]

permissions:
  auction.*:
    description: Gives access to all auction commands
    children:
      auction.admin: true
      auction.start: true
      auction.bid: true
  auction.admin:
    description: Auction administrative functions.
    default: op
  auction.start:
    description: Allows one to start an auction.
    default: op
  auction.bid:
    description: Allows one to bid on auctions.
    default: op
