name: floAuction
version: 2.1.0
description: Auction plugin for economies.
author: flobi
website: http://www.hollowmatrix.com/
depend: [WhatIsIt, Vault]

main: com.flobi.floAuction.floAuction
database: false
depend: [Vault, WhatIsIt]

commands:
  auction:
    description: General auction command.
    permission: auction.start
    usage: Type /<command> for instructions.
  bid:
    description: Bid on auctions.
    permission: auction.bid
    usage: /<command> [bit amount] [max bid]

permissions:
  auction.*:
    description: Gives access to all auction commands
    children:
      auction.admin: true
      auction.start: true
      auction.bid: true
  auction.admin:
    description: Auction administrative functions.
    default: op
  auction.start:
    description: Allows one to start an auction.
    default: op
  auction.bid:
    description: Allows one to bid on auctions.
    default: op
